<?php

namespace Link0\ProfilingDoctrineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ManyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManyRepository extends EntityRepository
{
}
